# TIP:
# The `brew` table might not need creation at all if you are planning to backup your existing formula/cask names only.
# Just run `cutler brew backup` to create it automatically in your configuration file.

[brew]
casks = [
    "android-studio",
    "zed",
    "zulu@21",
]
formulae = ["rust", "python3", "mise", "ruby", "cmatrix", "fastfetch"]
taps = ["machlit/tap"]
no_deps = true # Use this if you do not want cutler to check for dependencies when comparing.
