[book]
title = "the cutler cookbook"
authors = ["Machlit"]
description = "Documentation for cutler - a fast, declarative settings manager for the Mac"
language = "en"
src = "src"

[output.html]
default-theme = "machlight"
preferred-dark-theme = "machlit"
additional-css = ["./theme/machlit.css", "./theme/machlight.css"]

[output.html.search]
limit-results = 15
